# Generated by Django 4.2.16 on 2026-03-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='query',
        ),
        migrations.RemoveField(
            model_name='query',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='query',
            name='author',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
